### ISSUE TITLE
Feature request: Allow entry creation and JSON download without logging in

### ISSUE THREAD

**Issue by zmanion** [CERTCC/cveClient#17]
Would be nice to be able to use the editor and then save/export/download JSON without having to authenticate to CVE Services.

**Comment by sei-vsarvepalli** [comment]
I think @sei-jpstroud has this somewhat working - https://sei-jpstroud.github.io/cveClient/ .  A valid minimalist CVE record is what should be downloaded with duty metadata fields. Below is an example.  We can also do a AJAX get of a CVE record that is already published verbatim for preloading the CVE data with a simple Load CVE button. 


```
{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "containers": {
        "cna": {
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Example product is vulnerable"
                }
            ],
            "affected": [
                {
                    "versions": [
                        {
                            "version": "1.1",
                            "status": "affected"
                        }
                    ],
                    "product": "Software",
                    "vendor": "Example"
                }
            ],
            "references": [
                {
                    "url": "https://www.example.com/"
                }
            ],
            "providerMetadata": {
                "orgId": "00000000-0000-0000-0000-000000000000"
            }
        }
    },
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-0000-0000",
        "assignerOrgId": "00000000-0000-0000-0000-000000000000"
    }
}
```

**Comment by sei-jpstroud** [comment]
Hey Vijay,

We got it working and I have been doing some tweaking on it since then. We currently just download everything that is entered in. You told me to strip out the provider metadata with the download because it requires the user to be signed in and so I have. In this example you have it though. This is the format of the JSON that we got downloading:
{
"descriptions":[{"lang":"en","value":"busted"}],
"affected":[{"versions":[{"version":"1.0","status":"affected"}],
"product":"Camry","vendor":"Toyota"}],"references":[{"url":"www.toyota.com"}]
}

I can definitely add these extra metadata fields now that the bulk of the challenging part has been completed. Please let me know your thoughts.

Sincerely,
John Stroud

**Comment by sei-vsarvepalli** [comment]
John,

Yeh - please add the metadata with the dummy example as provided here. It will be good to either prompt or give a text field for the CVE number and make the download file be called CVE-XXXX-XXXX.json where the CVE-XXXX-XXXX is what is entered by the user for the CVE number. 

Vijay

**Comment by sei-jpstroud** [comment]
Vijay,

Okay I will implement that.

Best,
John

**Comment by sei-vsarvepalli** [comment]
Should be resolved now.
